### ISSUE TITLE
FAILED BUILD on platform.sh

### ISSUE THREAD

**Issue by razplus** [Roomify/rfa_platform#3]
Drush Make failing to download all projects.  Specific errors:

Unable to download ckeditor from                                         [error]
      W: https://ckeditor.com/onlinebuilder/releases/minified/4.7.3/icy_orange/0.9/ckeditor_4.7.3_8e6efb8f2d4a.zip.

**Comment by salvoscala** [comment]
Hi @razplus, we've created a new build of Ckeditor ([here](https://github.com/Roomify/RfA/commit/787df8d5c5ce56a31afc1907953abb88113e1956) the commit). It'll be available on the next version of RfA.

Thanks!

**Comment by salvoscala** [comment]
This has been solved on the [Roomify for Accommodations 1.4.6](https://github.com/Roomify/RfA/releases/tag/1.4.6)
